### ISSUE TITLE
possible FV3 issues with hord=9 and kord_tm = 9 [CESM FV3]

### ISSUE THREAD

**Issue by jtruesdal** [NOAA-GFDL/GFDL_atmos_cubed_sphere#104]
The original port of FV3 to CESM/CAM was undertaken to assist NOAA/GFDL in the improvement of FV3 through exposure to the CESM community of users.  While running through some of the different horizontal advection and vertical remap schemes available via the FV3 namelist we discovered a few problems when running the Baroclinic wave test case under the NCAR CESM Community Atmosphere Model).  As an error in these tests would indicate a possible bug in FV3 I would like to verify if these are known issues with FV3.  The CESM FV3 version of the test case works correctly when using hord=-9 or kord=-9 or kord=-4 but when different values are chosen the model crashes or the solution is obviously wrong.  Have you tested and verified that hord=9 and kord=9 work correctly in the current version of FV3?  Can you rerun the Moist Baroclinic Wave test with these settings and verify that the solution looks correct?  https://www.gfdl.noaa.gov/fv3/fv3-applications/fv3-idealized-tests-3/
We are testing hydrostatic C96 30 levels but any similar resolution should be OK to compare given the severity of our errors.

Test 1:  hord = 9
Test 2: kord = 9
Test 3: kord = 4

The following are comments on the errors by Christiane Jablonowski an author of the Baroclinic wave test and one of our collaborators at the University of Michigan.

1) the selection of hord=9 leads to a severe wavenumber 4 response in the baroclinic wave test
case and ultimately blows up after 7.75 days (for C96L30)

2) the selection of kord_tm from the default -9 (remap of temperature) to +9 (remap of potential temperature)
sets the temperature to almost zero (most likely after the first remap step). The simulation continues but is incorrect
from now on. I also tested another kord setting, namely kord_tm = 4 (instead of -4) and the same happens.
Therefore, I conclude that it is not due to a specific kord, but due to the fact that the mapping of potential temperature
(positive kord) has a generic bug when setting the temperature after the remap.

**Comment by lharris4** [comment]
Hi, John. The option hord = 9 is a positive-definite advection scheme.
While this is an attractive option for positive-definite scalars (hord_tr
and possibly hord_dp) it should not be used for advection of vorticity,
which physically must be represented in both signs. This would likely lead
to instabilities, noise, and the crash you are describing. We recommend
using either 10 or 8 for low-resolution climate simulations.

We haven't maintained the capability to use positive values for kord_tm,
which remap potential temperature instead of virtual temperature. So it is
possible that it may not work correctly. We have identified a separate bug
for adiabatic = .true. that has a similar effect (pkz is computed
incorrectly and so T gets messed up) and so they may have similar causes.

Thanks,
Lucas

**Comment by wmputman** [comment]
The GMAO has maintained various vertical remap options, including potential temperature for NH and hydrostatic, as well as total energy for hydrostatic.

You can view remap code on GIThub: https://github.com/GEOS-ESM/GFDL_atmos_cubed_sphere/blob/geos/main/model/fv_mapz.F90

-- Bill Putman

William M Putman
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Cell: 240-778-5697
Desk: 301-286-2599

From: lharris4 ***@***.***>
Reply-To: NOAA-GFDL/GFDL_atmos_cubed_sphere ***@***.***>
Date: Tuesday, May 25, 2021 at 9:19 AM
To: NOAA-GFDL/GFDL_atmos_cubed_sphere ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [NOAA-GFDL/GFDL_atmos_cubed_sphere] possible FV3 issues with hord=9 and kord_tm = 9 [CESM FV3] (#104)

Hi, John. The option hord = 9 is a positive-definite advection scheme.
While this is an attractive option for positive-definite scalars (hord_tr
and possibly hord_dp) it should not be used for advection of vorticity,
which physically must be represented in both signs. This would likely lead
to instabilities, noise, and the crash you are describing. We recommend
using either 10 or 8 for low-resolution climate simulations.

We haven't maintained the capability to use positive values for kord_tm,
which remap potential temperature instead of virtual temperature. So it is
possible that it may not work correctly. We have identified a separate bug
for adiabatic = .true. that has a similar effect (pkz is computed
incorrectly and so T gets messed up) and so they may have similar causes.

Thanks,
Lucas

**Comment by jtruesdal** [comment]
Thanks Lucas and Bill this is all very helpful information.  I thought I'd bring @cjablano into the conversation since she is working with this code and discovered the issues.  Re hord=9, I think we should probably disallow any namelist options that don't make sense from a scientific standpoint. Lucas are there other namelist combinations that should also be checked, and result in an endrun or perhaps a warning to the user?  I'm happy to put these checks in and make a PR.  

Bill I've glanced through your updates and don't think it would be too much trouble to implement for out branch if Christiane thinks it worthwhile and she is able to validate the mods.  If these are validated I could also put these updates for review in a PR.  My only caveat is that my queue is pretty long at this point and it may take a little while.

**Comment by lharris4** [comment]
Hi, John. Anyone is welcome to add checks for hord_{tm,mt,vt} = 9 or -5, or
to merge in the Goddard total-energy remapping; that's the advantage of
open development :-) It will of course need to pass the usual regression
tests. We are hoping to set up a stronger automated testing regime in the
coming months.

Thanks,
Lucas
