### ISSUE TITLE
Implement Rayleigh damping on vertical velocity only through semi-implicit solver

### ISSUE THREAD

**Issue by KevinViner-NOAA** [NOAA-GFDL/GFDL_atmos_cubed_sphere#229]
**Is your feature request related to a problem? Please describe.**
Damping of the horizontal velocity, as is done currently, is more consistent with a hydrostatic model. A nonhydrostatic model can simply damp the vertical velocity directly through the semi-implicit solver to prevent reflections from the upper boundary, but it requires a much shorter damping time scale. This is generally useful, but may also solve a spread problem near the model top in the ensemble system.

**Describe the solution you'd like**
I want to implement the Klemp 2008 (MWR) sponge mechanism on vertical velocity through the vertical solver with a new namelist parameter tau_nh which is the damping time scale in seconds (~0.2 seconds). This provides a very effective, relatively thin, sponge layer.

**Describe alternatives you've considered**
I have tried a damper on perturbation pressure through the solver (since that fits the boundary conditions), but that was not very effective. The results with the w-sponge have been robust.

**Additional context**

**Comment by lharris4** [comment]
Hi, Kevin. Thank you for working on this.

After some thought I remembered that since perturbation pressure is not a
prognostic variable, damping it will only have a very indirect effect on
vertical velocities, and will not remove the source of the strongest
vertical velocities which are typically thermally-driven.

I can take a look once you have a PR ready.

Lucas
